# Generated by Django 5.1.2 on 2025-09-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofiles", "0006_alter_friendship_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendship",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
