# Generated by Django 5.1.2 on 2025-09-22 02:25

from django.db import DatabaseError, migrations, models


def _as_text_list(value):
    if isinstance(value, (list, tuple)):
        return ", ".join(str(item) for item in value if item not in (None, ""))
    if isinstance(value, str):
        return value
    return ""


def migrate_core_profiles(apps, schema_editor):
    try:
        CoreProfile = apps.get_model("core", "Profile")
    except LookupError:
        return

    try:
        legacy_profiles = CoreProfile.objects.all()
    except DatabaseError:
        return

    Profile = apps.get_model("userprofiles", "Profile")

    for legacy in legacy_profiles.iterator():
        profile, _ = Profile.objects.get_or_create(user_id=legacy.user_id)

        updated_fields = []

        if legacy.full_name and not profile.full_name:
            profile.full_name = legacy.full_name
            updated_fields.append("full_name")

        if legacy.bio and not profile.bio:
            profile.bio = legacy.bio
            updated_fields.append("bio")

        if legacy.criteria and not profile.criteria:
            profile.criteria = legacy.criteria
            updated_fields.append("criteria")

        if legacy.spotify_info and not profile.spotify_info:
            profile.spotify_info = legacy.spotify_info
            updated_fields.append("spotify_info")

        if legacy.appearance and not profile.appearance:
            profile.appearance = legacy.appearance
            updated_fields.append("appearance")

        hobbies_text = _as_text_list(getattr(legacy, "hobbies", None))
        if hobbies_text and not profile.hobbies:
            profile.hobbies = hobbies_text
            updated_fields.append("hobbies")

        interests_text = _as_text_list(getattr(legacy, "interests", None))
        if interests_text and not profile.interests:
            profile.interests = interests_text
            updated_fields.append("interests")

        movies_text = _as_text_list(getattr(legacy, "favorite_movies", None))
        if movies_text and not profile.favorite_movies:
            profile.favorite_movies = movies_text
            updated_fields.append("favorite_movies")

        books_text = _as_text_list(getattr(legacy, "favorite_books", None))
        if books_text and not profile.favorite_books:
            profile.favorite_books = books_text
            updated_fields.append("favorite_books")

        if legacy.profession and not profile.profession:
            profile.profession = legacy.profession
            updated_fields.append("profession")

        education_text = getattr(legacy, "education", None)
        if education_text and not profile.education_level:
            profile.education_level = education_text
            updated_fields.append("education_level")

        if legacy.privacy_settings and not profile.privacy_settings:
            profile.privacy_settings = legacy.privacy_settings
            updated_fields.append("privacy_settings")

        if updated_fields:
            profile.save(update_fields=updated_fields)


def noop(*_args, **_kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("userprofiles", "0007_friendship_is_confirmed"),
        ("core", "0002_alter_user_options_user_display_name_user_spotify_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="appearance",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="profile",
            name="criteria",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="profile",
            name="full_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="interests",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="privacy_settings",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="profile",
            name="spotify_info",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(migrate_core_profiles, noop),
    ]
