version: "3.9"

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-personalities}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: ["/bin/bash", "/app/scripts/entrypoint.sh"]
    env_file:
      - .env
    environment:
      # Fallbacks if DATABASE_URL not set
      - POSTGRES_DB=${POSTGRES_DB:-personalities}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_data:/app/backend/staticfiles

volumes:
  db_data:
  static_data:

