# Generated by Django 5.1.2 on 2025-09-12 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0002_alter_evaluation_unique_together"),
        ("evaluations", "0002_raterstats"),
    ]

    operations = []
