# Generated by Django 5.1.2 on 2025-09-12 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0003_merge_20250912_1643"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("ACTIVE", "Active")],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Evaluation Meta",
                "verbose_name_plural": "Evaluation Meta",
            },
        ),
        migrations.AlterModelOptions(
            name="raterstats",
            options={
                "verbose_name": "Rater Stats",
                "verbose_name_plural": "Rater Stats",
            },
        ),
        migrations.RemoveIndex(
            model_name="raterstats",
            name="evaluations_ratings_7259ac_idx",
        ),
        migrations.AlterField(
            model_name="raterstats",
            name="reliability",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterUniqueTogether(
            name="evaluation",
            unique_together={("evaluator", "subject", "criterion")},
        ),
        migrations.AddField(
            model_name="evaluationmeta",
            name="evaluation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluationmeta",
                to="evaluations.evaluation",
            ),
        ),
    ]
