# Generated by Django 5.1.2 on 2025-09-22 03:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoinBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coins", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coin_balance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Coin balance",
                "verbose_name_plural": "Coin balances",
            },
        ),
        migrations.CreateModel(
            name="ReputationMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(default=0.0)),
                (
                    "momentum",
                    models.FloatField(default=0.0, help_text="Derivative of recent reputation change."),
                ),
                (
                    "last_recalculated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reputation_metric",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reputation metric",
                "verbose_name_plural": "Reputation metrics",
            },
        ),
        migrations.CreateModel(
            name="CoinTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(help_text="Positive values credit coins; negative values deduct coins."),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("question_created", "Question created"),
                            ("answer_submitted", "Answer submitted"),
                            ("evaluation_received", "Evaluation received"),
                            ("evaluation_given", "Evaluation given"),
                        ],
                        max_length=64,
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="External identifier to ensure idempotency (e.g., question/answer/evaluation id).",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coin_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("reference_id__isnull", False)),
                        fields=("event_type", "reference_id"),
                        name="unique_economy_event_reference",
                    )
                ],
            },
        ),
    ]
