# Generated by Django 5.1.2 on 2025-09-22 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cointransaction",
            index=models.Index(fields=["user", "created_at"], name="economy_coi_user_id_eb0f2e_idx"),
        ),
        migrations.AddIndex(
            model_name="cointransaction",
            index=models.Index(fields=["created_at"], name="economy_coi_created_226b9c_idx"),
        ),
        migrations.AddIndex(
            model_name="cointransaction",
            index=models.Index(fields=["event_type"], name="economy_coi_event_t_54b3f7_idx"),
        ),
    ]
