# Generated by Django 5.1.2 on 2025-09-22 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import DatabaseError, migrations, models


def copy_core_posts(apps, schema_editor):
    try:
        CorePost = apps.get_model("core", "Post")
    except LookupError:
        return

    try:
        core_post_qs = CorePost.objects.all()
    except DatabaseError:
        return

    Post = apps.get_model("posts", "Post")

    for legacy in core_post_qs.iterator():
        Post.objects.update_or_create(
            id=legacy.id,
            defaults={
                "author_id": legacy.author_id,
                "title": legacy.title,
                "content": legacy.content,
                "likes": getattr(legacy, "likes", 0) or 0,
                "shares": getattr(legacy, "shares", 0) or 0,
                "tags": getattr(legacy, "tags", []) or [],
                "external_urls": getattr(legacy, "external_urls", {}) or {},
                "is_published": getattr(legacy, "is_published", True),
                "created_at": getattr(legacy, "created_at", None),
                "updated_at": getattr(legacy, "updated_at", None),
            },
        )


def copy_core_comments(apps, schema_editor):
    try:
        CoreComment = apps.get_model("core", "Comment")
    except LookupError:
        return

    try:
        core_comment_qs = CoreComment.objects.all()
    except DatabaseError:
        return

    Comment = apps.get_model("posts", "Comment")

    for legacy in core_comment_qs.iterator():
        Comment.objects.update_or_create(
            id=legacy.id,
            defaults={
                "post_id": legacy.post_id,
                "author_id": legacy.author_id,
                "content": legacy.content,
                "created_at": getattr(legacy, "created_at", None),
            },
        )


def forwards(apps, schema_editor):
    copy_core_posts(apps, schema_editor)
    copy_core_comments(apps, schema_editor)


def noop(*_args, **_kwargs):
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_alter_user_options_user_display_name_user_spotify_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("likes", models.PositiveIntegerField(default=0)),
                ("shares", models.PositiveIntegerField(default=0)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("external_urls", models.JSONField(blank=True, default=dict)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.RunPython(forwards, noop),
    ]
