# Generated by Django 5.1.2 on 2025-09-22 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="agreement_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="comment",
            name="humor_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="comment",
            name="quality_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="comment",
            name="safety_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name="CommentReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quality",
                    models.SmallIntegerField(
                        choices=[(-1, "negative"), (0, "neutral"), (1, "positive")],
                        default=0,
                    ),
                ),
                (
                    "agreement",
                    models.SmallIntegerField(
                        choices=[(-1, "negative"), (0, "neutral"), (1, "positive")],
                        default=0,
                    ),
                ),
                (
                    "humor",
                    models.SmallIntegerField(
                        choices=[(-1, "negative"), (0, "neutral"), (1, "positive")],
                        default=0,
                    ),
                ),
                (
                    "safety",
                    models.SmallIntegerField(
                        choices=[(-1, "negative"), (0, "neutral"), (1, "positive")],
                        default=0,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="posts.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("comment", "user")},
            },
        ),
    ]
