# Generated by Django 5.1.2 on 2025-09-22 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import DatabaseError, migrations, models


def copy_core_messages(apps, schema_editor):
    try:
        CoreMessage = apps.get_model("core", "Message")
    except LookupError:
        return

    try:
        core_qs = CoreMessage.objects.all()
    except DatabaseError:
        return

    Message = apps.get_model("messaging", "Message")

    for legacy in core_qs.iterator():
        Message.objects.update_or_create(
            id=legacy.id,
            defaults={
                "sender_id": legacy.sender_id,
                "recipient_id": legacy.recipient_id,
                "content": legacy.content,
                "ai_response": getattr(legacy, "ai_response", ""),
                "is_mystery_message": getattr(legacy, "is_mystery_message", False),
                "created_at": getattr(legacy, "created_at", None),
                "updated_at": getattr(legacy, "updated_at", None),
            },
        )


def forwards(apps, schema_editor):
    copy_core_messages(apps, schema_editor)


def noop(*_args, **_kwargs):
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_alter_user_options_user_display_name_user_spotify_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=1000)),
                ("ai_response", models.TextField(blank=True, max_length=2000)),
                ("is_mystery_message", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(forwards, noop),
    ]
