# Generated by Django 5.1.2 on 2025-09-22 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_options_user_display_name_user_spotify_id"),
        ("posts", "0001_initial"),
        ("messaging", "0001_initial"),
        ("userprofiles", "0008_profile_appearance_profile_criteria_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
