# Generated by Django 5.1.2 on 2025-09-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_message_recipient_remove_message_sender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="coin_balance",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
