name: Backend CI

on:
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"
  push:
    branches: ["main"]
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: django_project.settings
      DATABASE_URL: sqlite:///db.sqlite3
      SECRET_KEY: ci-test-key
      OPENAI_API_KEY: dummy-ci-key
      ENVIRONMENT: ci
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PYTHONUNBUFFERED: "1"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install -U pip
          pip install -r backend/requirements.txt

      - name: Lint
        run: make lint
          source .venv/bin/activate
          flake8 backend
      - name: Test
        run: make test
          python manage.py test
